### ISSUE TITLE
NET-0086: Create Milestone 0.1 UI/UX Design Guides

### ISSUE THREAD

**Issue by allendomingo** [allendomingo/StoreInventory#86]
**DoD**
- [x] Login page design (#78)
- [x] Landing page design (#79)
- [x] Sidebar design (#80)
- [x] User Management page design (#88)
- [x] Default placeholder for unimplemented pages design (#81)

**Design Guide Link (Output)**
[Figma Guide](https://www.figma.com/file/BiANw7dW9baU65f2Nafsbs/Inventory-App-Design-Guide)

**Relevant Stories**
- As a user, I want to be able to log in, to use the app. (#78)
- As a user, I want to be able to access different parts of the app easily. (#79)
- As a user, I want to be able to logout in (almost) every page. (#79)
- As a user, I want to be able to navigate between pages intuitively and easily. (#80)
- As an admin/manager, I want to be able to see the list of users, to be able to monitor them among other things, (#88)
- As an admin, I want to be able to manage the users, for security purposes. (#88)
- As a product owner and developer, I want to display a proper placeholder for pages that have not yet been implemented, to properly inform users. (#81)

**Comment by allendomingo** [comment]
Output: https://www.figma.com/file/BiANw7dW9baU65f2Nafsbs/Inventory-App-Design-Guide
Requesting input/comments @gachagas @RayAdrian @themoeboy @Abelbait @YuugenXCVII
